### ISSUE TITLE
Converting from desktop version to android

### ISSUE THREAD

**Issue by anubhavagr27** [mmm2016/mediapipemultihandstrackingapp#1]
You followed : https://gist.github.com/TheJLifeX/74958cc59db477a91837244ff598ef4a and I followed another repository of same guy.
Can you please help me in how to convert this desktop version code "https://github.com/TheJLifeX/mediapipe/tree/hand-mouvement-recognition" to build in android studio with gradle. I followed steps mentioned in this: "https://google.github.io/mediapipe/getting_started/android_archive_library.html#steps-to-use-a-mediapipe-aar-in-android-studio-with-gradle " and updated corresponding AAR and binarypb file
but got the error mentioned in above comments. Am I missing something?

**Comment by mmm2016** [comment]
> 您遵循的是：[https](https://gist.github.com/TheJLifeX/74958cc59db477a91837244ff598ef4a) : [//gist.github.com/TheJLifeX/74958cc59db477a91837244ff598ef4a，](https://gist.github.com/TheJLifeX/74958cc59db477a91837244ff598ef4a)而我遵循的是同一个人的另一个存储库。
> 能否请您帮我转换此桌面版本代码“ https://github.com/TheJLifeX/mediapipe/tree/hand-mouvement-recognition ”以使用gradle在android studio中进行构建。我遵循了其中提到的步骤：“ https://google.github.io/mediapipe/getting_started/android_archive_library.html#steps-to-use-a-mediapipe-aar-in-android-studio-with-gradle ”并更新了相应的AAR和binarypb文件，
> 但得到了以上注释中提到的错误。我想念什么吗？

error ？

**Comment by anubhavagr27** [comment]
2020-06-17 16:34:04.968 22992-22992/com.example.mediapipemultihandstrackingapp E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.mediapipemultihandstrackingapp, PID: 22992
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "pcond" referenced by "/data/app/com.example.mediapipemultihandstrackingapp-nipd88fHmFF7IxiujdWFQw==/lib/arm64/libmediapipe_jni.so"...
at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
at java.lang.System.loadLibrary(System.java:1667)
at com.example.mediapipemultihandstrackingapp.MainActivity.(MainActivity.java:38)
at java.lang.Class.newInstance(Native Method)
at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
at android.app.Instrumentation.newActivity(Instrumentation.java:1251)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3436)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3707)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2220)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:237)
at android.app.ActivityThread.main(ActivityThread.java:8019)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by anubhavagr27** [comment]
I also tried your way of recognizing sliding and scrolling movement but unable to do it because of not knowing exactly how to take  x_center and y_center.

**Comment by mmm2016** [comment]
> I also tried your way of recognizing sliding and scrolling movement but unable to do it because of not knowing exactly how to take x_center and y_center.

I have updated the code with relevant implementation code，If it helps you, please give me a star, thank you！

**Comment by anubhavagr27** [comment]
Thanks Alot!!
But I am unable to tun it with old aar as it showing this error
error: cannot find symbol
                                         ^
  symbol:   class RectProto
  location: package com.google.mediapipe.formats.proto

As, I want to remove the grey landmark points from my apk. Is there any other way to remove those landmarks?

**Comment by mmm2016** [comment]
> Thanks Alot!!
> But I am unable to tun it with old aar as it showing this error
> error: cannot find symbol
> ^
> symbol: class RectProto
> location: package com.google.mediapipe.formats.proto
> 
> As, I want to remove the grey landmark points from my apk. Is there any other way to remove those landmarks?

Modify renderer_gpu.pbtxt。build a new aar
`# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:input_image"
  input_stream: "detection_render_data"
 - input_stream: "landmark_render_data"
  input_stream: "handedness_render_data"
  input_stream: "rect_render_data"
  output_stream: "IMAGE_GPU:output_image"
}`

**Comment by mmm2016** [comment]
> Thanks Alot!!
> But I am unable to tun it with old aar as it showing this error
> error: cannot find symbol
> ^
> symbol: class RectProto
> location: package com.google.mediapipe.formats.proto
> 
> As, I want to remove the grey landmark points from my apk. Is there any other way to remove those landmarks?

Modify renderer_gpu.pbtxt。build a new aar
# Draws annotations and overlays them on top of the input images.
node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:input_image"
  input_stream: "detection_render_data"
 # input_stream: "landmark_render_data"
  input_stream: "handedness_render_data"
  input_stream: "rect_render_data"
  output_stream: "IMAGE_GPU:output_image"
}

**Comment by mmm2016** [comment]
Modify renderer_gpu.pbtxt ,build a new aar

`node {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:input_image"
  input_stream: "detection_render_data"
  input_stream: "landmark_render_data"
  input_stream: "handedness_render_data"
  input_stream: "rect_render_data"
  output_stream: "IMAGE_GPU:output_image"
}`

**Comment by mmm2016** [comment]
> Thanks Alot!!
> But I am unable to tun it with old aar as it showing this error
> error: cannot find symbol
> ^
> symbol: class RectProto
> location: package com.google.mediapipe.formats.proto
> 
> As, I want to remove the grey landmark points from my apk. Is there any other way to remove those landmarks?

You need to look at the source code yourself, so that you can really understand and get the effect you want. When I see your problem, I also go to the source code and modify it.
